version: 2
jobs:
  build:
    working_directory: ~/repo
    docker: 
      - image: circleci/python3.7.7

  steps:
    # obtain repo from github
    - checkout
    # create virtual env and installl dependencies
    - run:
        name: install dependencies
        command: |
          python3 -m venv venv
          . venv/bin/Activate
          pip install -r ./app/requirements.txt
    # - run:
    #     name: run tests
    #     command: |
    #       . venv/bin/Activate
    #       flake8 --exclude=venv* --statistics
    #       pytest -v --cov=app